import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import VisitPing from "@/components/telemetry/VisitPing";
import { Reveal } from "@/components/ui/Reveal";
import { getSiteUrl } from "@/lib/site-url";
import { isJournalEnabled } from "@/lib/v5/journal/flags";
import { isValidWeekId } from "@/lib/v5/journal/schema";
import { readJournalEntry } from "@/lib/v5/journal/storage";

import JournalAdoptionPing from "@/app/v5/journal/_components/JournalAdoptionPing";

/**
 * V5 Phase 9 Sub-PR 9.3 — per-week journal detail page.
 *
 * Renders one frozen JournalEntry. Triple-gated:
 *   1. `isJournalEnabled()` — operator flag.
 *   2. Week id passes syntactic validation
 *      (`isValidWeekId`).
 *   3. KV holds an entry for that week.
 *
 * Any closed gate → `notFound()` → 404.
 *
 * The detail page is FROZEN — once written, the entry never
 * mutates. No revalidate; the SSR HTML is the canonical
 * rendering until the cron overwrites the entry (which
 * happens only when the cron explicitly re-runs for the
 * same week, an operator decision).
 *
 * Voice
 *   The detail page reads the entry's templated narrative,
 *   the top 5 commits with their WHY paragraphs, the
 *   frozen infrastructure status counts, the experiments
 *   that were active, the planned-state counts, the
 *   failures that landed that week.
 *
 *   Reading flow: narrative → top commits → counts. The
 *   editorial discipline of /v5/operating preserved.
 */

interface JournalDetailPageProps {
  params: Promise<{ week: string }>;
}

export async function generateMetadata({
  params,
}: JournalDetailPageProps): Promise<Metadata> {
  const { week } = await params;
  if (!isJournalEnabled() || !isValidWeekId(week)) {
    return {
      title: "Not found",
      robots: { index: false, follow: false },
    };
  }
  const entry = await readJournalEntry(week);
  if (!entry) {
    return {
      title: "Not found",
      robots: { index: false, follow: false },
    };
  }
  const title = `Week ${week} — engineering journal | Emre Doğan`;
  const description = entry.narrative;
  const canonical = `${getSiteUrl()}/v5/journal/${week}`;
  return {
    title,
    description,
    alternates: { canonical },
    openGraph: {
      title,
      description,
      url: canonical,
      type: "article",
    },
    robots: { index: true, follow: true },
  };
}

const COMMIT_BASE = "https://github.com/emredogan-cloud/my-portfolio/commit";
const REPO_BASE = "https://github.com/emredogan-cloud/my-portfolio/blob/main";

export default async function JournalDetailPage({
  params,
}: JournalDetailPageProps) {
  const { week } = await params;
  if (!isJournalEnabled()) notFound();
  if (!isValidWeekId(week)) notFound();
  const entry = await readJournalEntry(week);
  if (!entry) notFound();

  return (
    <main id="main" className="relative min-h-screen bg-black">
      <div
        className="pointer-events-none fixed inset-0 z-0"
        aria-hidden="true"
      >
        <div
          className="absolute top-[-200px] right-[-200px] w-[700px] h-[700px] rounded-full blur-[180px]"
          style={{
            background:
              "radial-gradient(ellipse, rgba(0,210,255,0.07) 0%, transparent 70%)",
          }}
        />
        <div
          className="absolute bottom-[-200px] left-[-100px] w-[600px] h-[600px] rounded-full blur-[160px]"
          style={{
            background:
              "radial-gradient(ellipse, rgba(0,210,255,0.04) 0%, transparent 70%)",
          }}
        />
      </div>

      <VisitPing surface="journal" />

      <div className="relative z-10 max-w-3xl mx-auto px-6 pt-36 pb-32">
        {/* EYEBROW */}
        <Reveal mode="mount" duration={0.7} className="mb-7">
          <div className="flex items-center gap-3">
            <span className="font-mono uppercase tracking-[0.20em] text-[10px] text-tertiary">
              V5
            </span>
            <span aria-hidden="true" className="font-mono text-[10px] text-faint">
              /
            </span>
            <span className="font-mono uppercase tracking-[0.20em] text-[10px] text-[#00d2ff]/80">
              Journal · {entry.week_id}
            </span>
            <span
              className="ml-auto px-2.5 py-1 rounded-full border font-mono uppercase tracking-[0.18em] text-[9px] border-[#00d2ff]/30 bg-[#00d2ff]/[0.04] text-[#00d2ff]/80"
              title="One frozen weekly digest, generated by the operational twin cron."
            >
              Phase 9 · weekly
            </span>
          </div>
        </Reveal>

        {/* HERO */}
        <Reveal mode="mount" duration={0.8} className="mb-12">
          <h1 className="text-4xl md:text-6xl font-medium tracking-[-0.04em] leading-[0.95] text-primary">
            <span className="block">Week {entry.week_id}.</span>
            <span className="block text-tertiary">
              {entry.week_start} → {entry.week_end}
            </span>
          </h1>
          <p className="text-secondary max-w-2xl mt-7 text-base md:text-lg leading-relaxed">
            {entry.narrative}
          </p>
          <p className="text-tertiary text-[13px] leading-relaxed mt-4 max-w-2xl">
            Frozen at{" "}
            <time
              dateTime={entry.generated_at}
              className="font-mono text-tertiary tabular-nums"
            >
              {entry.generated_at.slice(0, 19).replace("T", " ")} UTC
            </time>
            . The data below is what the operational twin saw
            at that moment;{" "}
            <Link
              href="/v5/operating"
              className="text-[#00d2ff]/80 hover:text-[#00d2ff] underline underline-offset-2 decoration-white/15 hover:decoration-[#00d2ff]/50 transition-colors"
            >
              /v5/operating
            </Link>{" "}
            shows current state.
          </p>
        </Reveal>

        {/* TOP COMMITS */}
        <Reveal duration={0.7} className="mb-14">
          <h2 className="font-mono uppercase tracking-[0.20em] text-[11px] text-tertiary mb-5">
            01 · The week&apos;s commits
          </h2>
          <p className="text-secondary text-sm leading-relaxed mb-6 max-w-2xl">
            {entry.weekly_summary.total_commits === 0
              ? "No commits in this window — observation week."
              : `${entry.weekly_summary.total_commits} commits, ${entry.weekly_summary.repos_touched} repo${entry.weekly_summary.repos_touched === 1 ? "" : "s"} touched. Top ${entry.weekly_summary.top_commits.length}, selected by the depth of their WHY paragraph.`}
          </p>
          {entry.weekly_summary.top_commits.length === 0 ? null : (
            <ul className="space-y-4">
              {entry.weekly_summary.top_commits.map((commit) => (
                <li
                  key={commit.sha}
                  className="border border-white/[0.06] rounded-xl bg-white/[0.02] p-5"
                >
                  <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1 mb-2">
                    <code className="font-mono text-[11px] text-[#00d2ff]/80">
                      {commit.sha}
                    </code>
                    {commit.type ? (
                      <span className="font-mono uppercase tracking-[0.18em] text-[9px] text-tertiary">
                        {commit.type}
                      </span>
                    ) : null}
                    <time
                      dateTime={commit.timestamp}
                      className="ml-auto font-mono text-[11px] text-tertiary tabular-nums"
                    >
                      {commit.timestamp.slice(0, 10)}
                    </time>
                  </div>
                  <p className="text-primary text-[14px] leading-snug mb-2">
                    <Link
                      href={commit.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:text-[#00d2ff] transition-colors"
                    >
                      {commit.subject}
                    </Link>
                  </p>
                  {commit.why ? (
                    <p className="text-secondary text-[13px] leading-relaxed">
                      {commit.why}
                    </p>
                  ) : null}
                </li>
              ))}
            </ul>
          )}
        </Reveal>

        {/* COUNTS */}
        <Reveal duration={0.7} className="mb-14">
          <h2 className="font-mono uppercase tracking-[0.20em] text-[11px] text-tertiary mb-5">
            02 · State at the freeze
          </h2>
          <p className="text-secondary text-sm leading-relaxed mb-6 max-w-2xl">
            The counts the operational twin saw at the
            moment this entry was generated.
          </p>
          <dl className="grid grid-cols-2 md:grid-cols-3 gap-3">
            <div className="border border-white/[0.06] rounded-xl bg-white/[0.02] p-4">
              <dt className="font-mono uppercase tracking-[0.18em] text-[9px] text-tertiary mb-1">
                Active infra
              </dt>
              <dd className="font-mono text-[20px] text-primary leading-none tabular-nums">
                {entry.infra_status_summary.active}
              </dd>
            </div>
            <div className="border border-white/[0.06] rounded-xl bg-white/[0.02] p-4">
              <dt className="font-mono uppercase tracking-[0.18em] text-[9px] text-tertiary mb-1">
                Dormant
              </dt>
              <dd className="font-mono text-[20px] text-primary leading-none tabular-nums">
                {entry.infra_status_summary.dormant}
              </dd>
            </div>
            <div className="border border-white/[0.06] rounded-xl bg-white/[0.02] p-4">
              <dt className="font-mono uppercase tracking-[0.18em] text-[9px] text-tertiary mb-1">
                Archived
              </dt>
              <dd className="font-mono text-[20px] text-primary leading-none tabular-nums">
                {entry.infra_status_summary.archived}
              </dd>
            </div>
            <div className="border border-white/[0.06] rounded-xl bg-white/[0.02] p-4">
              <dt className="font-mono uppercase tracking-[0.18em] text-[9px] text-tertiary mb-1">
                Experiments
              </dt>
              <dd className="font-mono text-[20px] text-primary leading-none tabular-nums">
                {entry.experiments_active.length}
              </dd>
            </div>
            <div className="border border-white/[0.06] rounded-xl bg-white/[0.02] p-4">
              <dt className="font-mono uppercase tracking-[0.18em] text-[9px] text-tertiary mb-1">
                In progress
              </dt>
              <dd className="font-mono text-[20px] text-primary leading-none tabular-nums">
                {entry.planned_state.in_progress}
              </dd>
            </div>
            <div className="border border-white/[0.06] rounded-xl bg-white/[0.02] p-4">
              <dt className="font-mono uppercase tracking-[0.18em] text-[9px] text-tertiary mb-1">
                Planned
              </dt>
              <dd className="font-mono text-[20px] text-primary leading-none tabular-nums">
                {entry.planned_state.next_up +
                  entry.planned_state.considering +
                  entry.planned_state.draft}
              </dd>
            </div>
          </dl>
        </Reveal>

        {/* CORRECTIONS */}
        {entry.recent_failures_added.length > 0 ? (
          <Reveal duration={0.7} className="mb-14">
            <h2 className="font-mono uppercase tracking-[0.20em] text-[11px] text-tertiary mb-5">
              03 · Corrections recorded this week
            </h2>
            <ul className="space-y-4">
              {entry.recent_failures_added.map((failure) => (
                <li
                  key={failure.id}
                  className="border border-white/[0.06] rounded-xl bg-white/[0.02] p-5"
                >
                  <div className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1 mb-2">
                    <span className="font-mono uppercase tracking-[0.18em] text-[10px] text-[#00d2ff]/80">
                      {failure.category}
                    </span>
                    <time
                      dateTime={failure.date}
                      className="font-mono text-[11px] text-tertiary tabular-nums"
                    >
                      {failure.date}
                    </time>
                  </div>
                  <h3 className="text-primary text-[14px] leading-snug mb-2">
                    {failure.title}
                  </h3>
                  <p className="text-secondary text-[13px] leading-relaxed">
                    {failure.fix}
                  </p>
                  {failure.commitSha ? (
                    <p className="mt-2">
                      <Link
                        href={`${COMMIT_BASE}/${failure.commitSha}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="font-mono text-[10px] text-tertiary hover:text-[#00d2ff] transition-colors"
                      >
                        commit {failure.commitSha}
                      </Link>
                    </p>
                  ) : null}
                </li>
              ))}
            </ul>
          </Reveal>
        ) : null}

        {/* RELATED */}
        <Reveal duration={0.7} className="mb-14">
          <h2 className="font-mono uppercase tracking-[0.20em] text-[11px] text-tertiary mb-5">
            04 · Related
          </h2>
          <ul className="divide-y divide-white/[0.06] border-t border-b border-white/[0.06]">
            <li>
              <Link
                href="/v5/journal"
                className="block py-4 grid grid-cols-1 md:grid-cols-[180px_1fr] gap-2 md:gap-6 hover:bg-white/[0.02] -mx-2 px-2 transition-colors rounded"
              >
                <span className="font-mono uppercase tracking-[0.18em] text-[10px] text-tertiary">
                  /v5/journal
                </span>
                <span>
                  <span className="font-mono text-[13px] text-[#00d2ff]/90 block">
                    Journal index
                  </span>
                  <span className="text-secondary text-[13px] mt-1 block leading-relaxed">
                    Every weekly entry, newest first.
                  </span>
                </span>
              </Link>
            </li>
            <li>
              <Link
                href="/v5/operating"
                className="block py-4 grid grid-cols-1 md:grid-cols-[180px_1fr] gap-2 md:gap-6 hover:bg-white/[0.02] -mx-2 px-2 transition-colors rounded"
              >
                <span className="font-mono uppercase tracking-[0.18em] text-[10px] text-tertiary">
                  /v5/operating
                </span>
                <span>
                  <span className="font-mono text-[13px] text-[#00d2ff]/90 block">
                    Live operational portrait
                  </span>
                  <span className="text-secondary text-[13px] mt-1 block leading-relaxed">
                    The CURRENT state of the system. This
                    entry is what it was at one specific
                    moment.
                  </span>
                </span>
              </Link>
            </li>
            <li>
              <Link
                href={`${REPO_BASE}/lib/v5/journal/generator.ts`}
                target="_blank"
                rel="noopener noreferrer"
                className="block py-4 grid grid-cols-1 md:grid-cols-[180px_1fr] gap-2 md:gap-6 hover:bg-white/[0.02] -mx-2 px-2 transition-colors rounded"
              >
                <span className="font-mono uppercase tracking-[0.18em] text-[10px] text-tertiary">
                  Generator source
                </span>
                <span>
                  <span className="font-mono text-[13px] text-[#00d2ff]/90 block">
                    lib/v5/journal/generator.ts
                  </span>
                  <span className="text-secondary text-[13px] mt-1 block leading-relaxed">
                    The pure function that built this entry
                    from the operational snapshot.
                    Templated narrative, no LLM.
                  </span>
                </span>
              </Link>
            </li>
          </ul>
        </Reveal>

        {/* FOOTER */}
        <Reveal duration={0.7}>
          <div className="border-t border-white/[0.05] pt-6 mt-12 space-y-3">
            <p className="font-mono uppercase tracking-[0.20em] text-[10px] text-quiet flex flex-wrap items-center gap-x-3 gap-y-1">
              <span
                aria-hidden="true"
                className="inline-block w-1 h-1 rounded-full bg-[#00d2ff]/70 align-middle"
              />
              <span>V5 · Phase 9 · Weekly entry · {entry.week_id}</span>
              <span className="text-faint">·</span>
              <span>Frozen artifact</span>
              <span className="text-faint">·</span>
              <span>Templated, not LLM-narrated</span>
            </p>
          </div>
        </Reveal>

        {/* Adoption ping — once per session per week. */}
        <JournalAdoptionPing kind="entry_view" slug={entry.week_id} />
      </div>
    </main>
  );
}
