"use client";

import { useCallback, useEffect, useRef, useState } from "react";

/**
 * AudioPlayer — minimal HTML5 audio surface for the Listen tab
 * on `/notes/[slug]`.
 *
 * V4 Phase 2 — Sub-PR 2.5.
 *
 * Posture decisions:
 *   - Native `<audio>` element. No custom canvas waveform, no
 *     external SDK, no fake-playback skeleton. The browser's
 *     built-in player already handles seek, play/pause, volume,
 *     and accessibility better than any custom widget. The cap is
 *     ~20 lines of CSS to make it match the site's cyan-on-black
 *     vocabulary.
 *   - Graceful degradation. When `public/notes/audio/<slug>.mp3`
 *     doesn't exist yet (typical between merge and the first
 *     `regenerate-audio` cron firing), the browser emits an
 *     `error` event — we swap the player for a quiet "audio
 *     pending" mono row instead of leaving the broken player UI
 *     visible.
 *   - Telemetry on first play. Posts once per session to
 *     `/api/telemetry/visit?surface=notes-audio-play`. Guarded by
 *     a sessionStorage flag so a curious visitor scrubbing the
 *     timeline can't run up the counter.
 *   - `keepalive: true` on the fetch so the request survives the
 *     visitor navigating away mid-play.
 */

interface AudioPlayerProps {
  src: string;
  duration?: string;
  /** Slug threaded through for the telemetry session-flag so two
   *  notes tracked separately in the same tab session don't
   *  collide. */
  slug: string;
}

const STORAGE_PREFIX = "v4:telemetry:notes-audio-play:";

export default function AudioPlayer({ src, duration, slug }: AudioPlayerProps) {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const [error, setError] = useState<boolean>(false);

  /* Fire the once-per-session telemetry ping when the visitor
   * actually presses play. Calling it inside an effect would
   * fire on mount; we want the *play* event so a passive scroll
   * past the Listen tab doesn't count. */
  const handlePlay = useCallback(() => {
    const key = `${STORAGE_PREFIX}${slug}`;
    try {
      if (sessionStorage.getItem(key) === "fired") return;
      sessionStorage.setItem(key, "fired");
    } catch {
      /* sessionStorage blocked — accept one extra count per
       * page load in that edge case. */
    }
    void fetch("/api/telemetry/visit", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ surface: "notes-audio-play" }),
      keepalive: true,
    }).catch(() => {
      /* swallow — telemetry never blocks the player */
    });
  }, [slug]);

  /* Attach the error listener once. Native `<audio>` doesn't
   * support React's onError reliably across browsers; native
   * addEventListener is the dependable path. */
  useEffect(() => {
    const el = audioRef.current;
    if (!el) return;
    const onError = () => setError(true);
    el.addEventListener("error", onError);
    return () => el.removeEventListener("error", onError);
  }, []);

  if (error) {
    return (
      <div className="rounded-2xl border border-white/[0.06] bg-white/[0.018] p-5 md:p-6 min-h-[80px] flex items-center">
        <p className="font-mono uppercase tracking-[0.20em] text-[10px] text-quiet flex flex-wrap items-center gap-x-3 gap-y-1">
          <span
            aria-hidden="true"
            className="inline-block w-1 h-1 rounded-full bg-[#00d2ff]/60 align-middle"
          />
          <span>Audio pending</span>
          <span className="text-faint">·</span>
          <span>generated by the weekly cron, served from public/</span>
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-white/[0.06] bg-white/[0.018] p-5 md:p-6">
      <div className="flex items-center justify-between gap-3 mb-3">
        <span className="font-mono uppercase tracking-[0.20em] text-[10px] text-[#00d2ff]/80">
          Listen
        </span>
        {duration && (
          <span className="font-mono uppercase tracking-[0.18em] text-[9px] text-quiet">
            {duration}
          </span>
        )}
      </div>
      <audio
        ref={audioRef}
        src={src}
        controls
        preload="metadata"
        onPlay={handlePlay}
        className="w-full"
        style={{
          /* Coerce the native player's accent toward the brand
           * cyan on browsers that honour the CSS property. Safari
           * + Chromium pick it up; Firefox draws its own native
           * controls regardless. Acceptable degradation. */
          accentColor: "#00d2ff",
          colorScheme: "dark",
        }}
      >
        Your browser does not support the audio element.
      </audio>
      <p className="font-mono uppercase tracking-[0.18em] text-[9px] text-quiet mt-3 flex flex-wrap items-center gap-x-3 gap-y-1">
        <span>Generated by ElevenLabs</span>
        <span className="text-faint">·</span>
        <span>refreshed weekly</span>
        <span className="text-faint">·</span>
        <span>not persisted between sessions</span>
      </p>
    </div>
  );
}
